version: '3.8'

services:
  mongodb:
  image: mongo:6.0
  container_name: supermercado_mongo
  ports:
    - "27018:27017"  # puerto externo 27018 para evitar conflicto
  command: ["--noauth"]


  backend:
    build: .
    container_name: supermercado_backend
    ports:
      - "4000:4000"
    depends_on:
      - mongodb
    environment:
      - MONGO_URL=mongodb://mongodb:27017
    volumes:
      - .:/app

  frontend:
    image: nginx:stable-alpine
    container_name: supermercado_frontend
    ports:
      - "8080:80"
    volumes:
      - ./fronted:/usr/share/nginx/html:ro
    depends_on:
      - backend

volumes:
  mongo_data:
